apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hok-admin
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hok-admin
subjects:
- kind: ServiceAccount
  name: hok-admin
  namespace: {{ .Values.teamname }}
roleRef:
  kind: ClusterRole
  name: hok-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hok-admin
  namespace: {{ .Values.teamname }}